/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type Status =
	| 'open'
	| 'investigating'
	| 'identified'
	| 'monitoring'
	| 'resolved'
	| 'archived';
export type Description = string;
export type Impact = string;

export interface IncidentData {
	status?: Status;
	description?: Description;
	impact?: Impact;
	mirrors?: string[];
	[k: string]: unknown;
}

export interface IncidentContractDefinition
	extends ContractDefinition<IncidentData> {}

export interface IncidentContract extends Contract<IncidentData> {}
