/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type Title = string;
export type Description = string;
export type Impact = string;
export type Status =
	| 'open'
	| 'investigating'
	| 'identified'
	| 'monitoring'
	| 'resolved'
	| 'archived';

export interface IncidentData {
	service?: Title;
	description?: Description;
	impact?: Impact;
	mirrors?: string[];
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	status: Status;
	[k: string]: unknown;
}

export interface IncidentContractDefinition
	extends ContractDefinition<IncidentData> {}

export interface IncidentContract extends Contract<IncidentData> {}
