/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type Title = string | null;
export type Details = string;

export interface PostMortemData {
	title?: Title;
	details?: Details;
	[k: string]: unknown;
}

export interface PostMortemContractDefinition
	extends ContractDefinition<PostMortemData> {}

export interface PostMortemContract extends Contract<PostMortemData> {}
