/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface StatuspageData {
	name?: string;
	description?: string;
	domain?: string;
	subdomain: string;
	mirrors?: string[];
	[k: string]: unknown;
}

export interface StatuspageContractDefinition
	extends ContractDefinition<StatuspageData> {}

export interface StatuspageContract extends Contract<StatuspageData> {}
